name: Build frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yaml"
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/yasinbb00/ocp-guestbook/
  IMAGE_REGISTRY: ghcr.io/yasinbb00/ocp-guestbook
  IMAGE_NAME: frontend
  INFRA_REPO: yasinbb00/guest-book-infra

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image tag
        id: image-tag
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          IMAGE_TAG="1.0.${GITHUB_RUN_NUMBER}-${SHORT_SHA}"
          echo "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "Generated tag: ${IMAGE_TAG}"
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/yasinbb00/ocp-guestbook/frontend:latest
            ghcr.io/yasinbb00/ocp-guestbook/frontend:${{ steps.image-tag.outputs.tag }}

      - name: Update Kubernetes manifests
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git clone https://${{ secrets.guest_book_infra }}@github.com/${{ env.INFRA_REPO }}.git guest-book-infra
          cd guest-book-infra

          sed -i "s|image: .frontend:.|image: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}|" k8s/frontend.yaml
          sed -i 's|value: ".*"|value: "${{ steps.image-tag.outputs.tag }}"|' k8s/frontend.yaml

          git add k8s/frontend.yaml
          git commit -m "Updated frontend image to ${{ steps.image-tag.outputs.tag }}"
          git push origin main